-- MySQL Script generated by MySQL Workbench
-- Fri Dec  3 08:30:30 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Estádios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Estádios` (
  `nome` VARCHAR(45) NOT NULL,
  `capacidade` VARCHAR(45) NULL,
  `cidade` VARCHAR(45) NULL,
  PRIMARY KEY (`nome`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Jogadores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Jogadores` (
  `nome` VARCHAR(45) NOT NULL,
  `idade` INT NULL,
  `clube` VARCHAR(45) NULL,
  PRIMARY KEY (`nome`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Times`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Times` (
  `nome` VARCHAR(45) NOT NULL,
  `qtd_titulos` INT NULL,
  `data_criacao` DATE NULL,
  `posição_do_campeonato` INT NULL,
  `pontos` INT NULL,
  `Jogadores_nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nome`),
  INDEX `fk_Times_Jogadores1_idx` (`Jogadores_nome` ASC) VISIBLE,
  CONSTRAINT `fk_Times_Jogadores1`
    FOREIGN KEY (`Jogadores_nome`)
    REFERENCES `mydb`.`Jogadores` (`nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Arbitragem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Arbitragem` (
  `nome` VARCHAR(45) NOT NULL,
  `funcao` VARCHAR(45) NULL,
  `pais_de_origem` VARCHAR(45) NULL,
  PRIMARY KEY (`nome`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Jogos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Jogos` (
  `data` DATETIME NULL,
  `n_gols` INT NULL,
  `n_faltas` INT NULL,
  `n_cartaoV` INT NULL,
  `n_cartaoA` INT NULL,
  `horario_inicio` DATETIME NULL,
  `horario_final` DATETIME NULL,
  `id_partida` INT NOT NULL,
  `Times_nome` VARCHAR(45) NOT NULL,
  `Arbitragem_nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_partida`),
  INDEX `fk_Jogos_Times1_idx` (`Times_nome` ASC) VISIBLE,
  INDEX `fk_Jogos_Arbitragem1_idx` (`Arbitragem_nome` ASC) VISIBLE,
  CONSTRAINT `fk_Jogos_Times1`
    FOREIGN KEY (`Times_nome`)
    REFERENCES `mydb`.`Times` (`nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Jogos_Arbitragem1`
    FOREIGN KEY (`Arbitragem_nome`)
    REFERENCES `mydb`.`Arbitragem` (`nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Copa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Copa` (
  `ano` YEAR NOT NULL,
  `país_cede` VARCHAR(45) NULL,
  `Estádios_nome` VARCHAR(45) NOT NULL,
  `Jogos_id_partida` INT NOT NULL,
  PRIMARY KEY (`ano`),
  INDEX `fk_Copa_Estádios1_idx` (`Estádios_nome` ASC) VISIBLE,
  INDEX `fk_Copa_Jogos1_idx` (`Jogos_id_partida` ASC) VISIBLE,
  CONSTRAINT `fk_Copa_Estádios1`
    FOREIGN KEY (`Estádios_nome`)
    REFERENCES `mydb`.`Estádios` (`nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Copa_Jogos1`
    FOREIGN KEY (`Jogos_id_partida`)
    REFERENCES `mydb`.`Jogos` (`id_partida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Stats da partida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Stats da partida` (
  `qtd_faltas` INT NULL,
  `qtd_gols` INT NULL,
  `qtd_assists` INT NULL,
  `Jogadores_nome` VARCHAR(45) NOT NULL,
  `Jogos_id_partida` INT NOT NULL,
  PRIMARY KEY (`Jogadores_nome`),
  INDEX `fk_Stats da partida_Jogos1_idx` (`Jogos_id_partida` ASC) VISIBLE,
  CONSTRAINT `fk_Stats da partida_Jogadores1`
    FOREIGN KEY (`Jogadores_nome`)
    REFERENCES `mydb`.`Jogadores` (`nome`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Stats da partida_Jogos1`
    FOREIGN KEY (`Jogos_id_partida`)
    REFERENCES `mydb`.`Jogos` (`id_partida`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
